### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by pcav** [SpatialVision/qgis_scipy_clustering#3]
A quick test gave:

"/home/paolo/.qgis2/python/plugins/processing/core/GeoAlgorithm.py", line 227, in execute|    self.processAlgorithm(progress)|  File "/home/paolo/.qgis2/python/plugins/ScipyPointClustering/scipy_point_clustering_algorithm.py", line 158, in processAlgorithm|    metric=metric|  File "/usr/lib/python2.7/dist-packages/scipy/cluster/hierarchy.py", line 1684, in fclusterdata|    Y = distance.pdist(X, metric=metric)|  File "/usr/lib/python2.7/dist-packages/scipy/spatial/distance.py", line 1220, in pdist|    dm = np.zeros((m \* (m - 1)) // 2, dtype=np.double)|MemoryError|

**Comment by pcav** [comment]
On a smaller layer it works fine

**Comment by om-henners** [comment]
@pcav How many points were in the original dataset? There is a known issue with the hierarchical clustering in the scipy library (see https://github.com/scipy/scipy/issues/3563) - the linkage matrix requires O(n^2) to store distances, meaning larger datasets will quickly fall over with memory issues. I'll add a warning to the algorithm about the memory, but I'm open to suggestions on what I could do further.

**Comment by pcav** [comment]
> 70k
> A warning will be OK, but of course this is a serious limitation.
> Perhaps it should be clarified in the About.
> Thanks.

**Comment by om-henners** [comment]
@pcav I've added an option to the Processing options to give a limit to the number of points that can be processed in the hierarchical cluster algorithms. The k-means isn't as badly affected by this limit so I've not put in the same limit in that algorithm. I've also updated the plugin to 0.2 which I'll now put up in the plugin repository.
